apiVersion: apps/v1
kind: Deployment
metadata:
  name: Linnovate-deployment
spec:
  selector:
    matchLabels:
      app: Linnovate-app
  replicas: 3
  template:
    metadata:
      labels:
        app: Linnovate-app
    spec:
      containers:
      - name: Linnovate-app
        image: ofiraviv/nginx-php-fpm:$BUILD_NUMBER
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Linnovate-service
spec:
  selector:
    app: Linnovate-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer