apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
data:
 config : |
   server {
       listen 80 default_server;
       client_max_body_size 500M;
       server_name localhost;
       root /app;
       error_log /var/log/nginx/error.log;
       access_log /var/log/nginx/access.log;
       index index.html index.php;
       location / {
           try_files $uri $uri /index.php$is_args$args;
       }
       location ~ ^/.+\.php(/|$) {
           fastcgi_split_path_info ^(.+?\.php)(/.*)$;
           if (!-f $document_root$fastcgi_script_name) {
               return 404;
           }
           include fastcgi_params;
           fastcgi_pass localhost:9000;
           fastcgi_index index.php;
           fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
           fastcgi_param DOCUMENT_ROOT $realpath_root;
           fastcgi_param REALPATHTEST $realpath_root;
           internal;
       }
   }
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: php-multiple-container
 name: php-multiple-container
spec:
 replicas: 1
 selector:
   matchLabels:
     app: php-multiple-container
 template:
   metadata:
     labels:
       app: php-multiple-container
   spec:
     containers:
     - image: ofiraviv/my-nginx:latest
       name: nginx
       volumeMounts:
       - mountPath: /etc/nginx/conf.d
         name: nginx-config
     - image: ofiraviv/my-php-app:latest
       name: php
     volumes:
     - name: nginx-config
       configMap:
         name: nginx-config
         items:
         - key: config
           path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
