apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: ofiraviv/my-php-app:latest
        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: php-fpm-nodeport-service
spec:
  type: NodePort
  selector:
    app: php-fpm
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000

