apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: ofiraviv/php-app:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  selector:
    type: ClusterIP
    app: php-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
