name: CI

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ofiraviv/nginx-php-fpm:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install and set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
      
      - name: Deploy to Minikube
        run: |
          kubectl config use-context minikube
          
          sed -i "s|ofiraviv/nginx-php-fpm:latest|ofiraviv/nginx-php-fpm:latest|g" deployment.yaml
          
          kubectl apply -f k8s/deployment.yaml

