name: Deploy to EKS - miceoservices

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      apply:
        type: boolean
        default: true
        required: true
        description: Start apply for the PHP-APP?

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install and configure kubectl
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - name: Build and push PHP Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:${{ github.sha }} .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:${{ github.sha }}

    - name: Setup PHP image
      id: setup_php_image
      run: echo "::set-output name=image::${{ secrets.DOCKERHUB_USERNAME }}/my-php-app:${{ github.sha }}"

    - name: Update PHP deployment
      run: |
          sed -i 's|image: .*|image: '${{ steps.setup_php_image.outputs.image }}'|' k8s/php-deployment.yaml

    - name: Build and push Nginx Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:${{ github.sha }} -f ./nginx.Dockerfile .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:${{ github.sha }}

    - name: Setup Nginx image
      id: setup_nginx_image
      run: echo "::set-output name=image::${{ secrets.DOCKERHUB_USERNAME }}/my-nginx:${{ github.sha }}"

    - name: Update Nginx deployment
      run: |
          sed -i 's|image: .*|image: '${{ steps.setup_nginx_image.outputs.image }}'|' k8s/nginx-deployment.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/php-deployment.yaml
        kubectl apply -f k8s/nginx-deployment.yaml
        kubectl apply -f k8s/nginx-ingress.yaml
